version: '3.6'
services:
  telegraf:
    image: telegraf:latest
    volumes:
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125/udp'

  influxdb:
    image: influxdb:latest
    env_file: config.env
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb/influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - influxdb
    env_file: config.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  k6:
    image: loadimpact/k6
    ports:
      - '6565:6565'
    environment:
      - K6_NO_USAGE_REPORT
    command: 'version'

volumes:
  grafana_data: {}
  influxdb_data: {}

